(function () {
    const _u = atob('aHR0cHM6Ly9naXN0LmdpdGh1YnVzZXJjb250ZW50LmNvbS9ERVZFTE9QRVIyNTAtQ09ERS8wMmIzYzZhYzliMzJjMjMzMThmZWMzN2RhMzg5ZWFiYi9yYXcvY29uZmlnLWh0bWwuanNvbg=='), _k = 'app_status', _d = 2500;
    let _o = null, _a = null, _m = 'This app is temporarily disabled.';
    function _c() { const e = document.createElement('div'); e.id = 'ks-overlay'; e.style.cssText = 'position:fixed;top:0;left:0;width:100%;height:100vh;background:#0d0d0d;display:flex;justify-content:center;align-items:center;z-index:999999;opacity:0;transition:opacity .4s cubic-bezier(.4,0,.2,1);font-family:"Google Sans",-apple-system,sans-serif;'; const t = document.createElement('div'); t.style.cssText = 'text-align:center;padding:48px 32px;max-width:360px;background:#1a1a1a;border-radius:28px;border:1px solid #2d2d2d;box-shadow:0 8px 32px rgba(0,0,0,.4);'; const n = document.createElement('div'); n.innerHTML = '<svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#8ab4f8" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><circle cx="12" cy="16" r="0.5" fill="#8ab4f8" stroke="none"/></svg>'; n.style.cssText = 'margin-bottom:24px;opacity:.9;'; const s = document.createElement('h2'); s.textContent = 'App Unavailable'; s.style.cssText = 'color:#e8eaed;font-size:24px;font-weight:500;margin-bottom:12px;letter-spacing:-.3px;'; const i = document.createElement('p'); i.id = 'ks-message'; i.textContent = _m; i.style.cssText = 'color:#9aa0a6;font-size:15px;line-height:1.5;font-weight:400;'; t.appendChild(n); t.appendChild(s); t.appendChild(i); e.appendChild(t); return e }
    function _s() { if (!_o) { _o = _c(); document.body.appendChild(_o); } else { document.getElementById('ks-message').textContent = _m; } _a && (_a.style.display = 'none'); requestAnimationFrame(() => { _o.style.opacity = '1'; }); }
    function _h() { _o && (_o.style.display = 'none'); _a && (_a.style.display = 'block'); }
    function _p(e, t) { try { const n = { active: e, message: t || null, timestamp: Date.now() }; localStorage.setItem(_k, JSON.stringify(n)); return !0 } catch (e) { return !1 } }
    function _g() { try { const e = localStorage.getItem(_k); if (e) { const t = JSON.parse(e); if (Date.now() - t.timestamp < 604800000) return { active: t.active, message: t.message } } } catch (e) { } return null }
    async function _f() { try { const e = new AbortController, t = setTimeout(() => e.abort(), 5000), n = await fetch(_u, { signal: e.signal, cache: 'no-cache', mode: 'cors' }); clearTimeout(t); if (!n.ok) { console.log(0); throw new Error() } const s = await n.json(); if (s && typeof s.active === 'boolean') { console.log(s.active ? 1 : 2); if (s.message) _m = s.message; return { active: s.active, message: s.message || null } } console.log(0); throw new Error() } catch (e) { console.log(0); throw e } }
    async function _vC() { await new Promise(e => setTimeout(e, _d)); try { const e = await _f(); _p(e.active, e.message); e.active ? _h() : _s(); return e.active } catch (e) { const t = _g(); if (t !== null) { if (t.message) _m = t.message; t.active ? _h() : _s(); return t.active } _h(); return !0 } }
    function _i() { _a = document.querySelector('.google-messages') || document.querySelector('.phone-app') || document.getElementById('app'); _vC().catch(e => { const t = _g(); if (t && t.message) _m = t.message; t && t.active === !1 ? _s() : _h(); }); }
    if (typeof cordova !== 'undefined') { document.addEventListener('deviceready', _i, false); } else { document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', _i) : _i(); }
})();